### ISSUE TITLE
git stash kontrolü yok

### ISSUE THREAD

**Issue by fatihhayri** [erayalakese/git-it#1]
Başka bir işten kalan dosya mevcut işte yeniden göründü

**Comment by hkulekci** [comment]
@fatihhayri @erayalakese you can check my pr #2

**Comment by erayalakese** [comment]
Eğer `rebase-with`komutu için konuşuyorsak, eepoda kalan commit edilmemiş değişiklikler varsa bunları kaybetmemek için stash'e atılıp rebase sonrası bu işleri eski haline getiriyor. Yanlış branch'teki dosyalar mı geliyor tam anlayamadım? @fatihhayri 

Gecikme için üzgünüm. Bu repoyu daha aktif takip edeceğim artık.

**Comment by erayalakese** [comment]
Problemi #2 'yi inceleyince anladım. Sorun ilgili PR merge edilerek çözüldü.
